### ISSUE TITLE
Implement page SEO for homepage and /blog

### ISSUE THREAD

**Issue by nickick** [OriginProtocol/story.xyz#1]
use values provided on `Story.xyz - Page SEO` [CMS data](https://origin-cms.herokuapp.com/admin/content-manager/collectionType/api::story.story-page-seo?page=1&pageSize=10&sort=page:ASC&plugins[i18n][locale]=en) for SEO and social share data on index and /blog pages.

**Comment by franckc** [comment]
@nickick I'm seeing the meta tags so I'm going to close this. Please re-open if there is any work remaining.
