### ISSUE TITLE
Add robots.txt and sitemap.xml

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/story.xyz#2]
The story.xyz is missing a robots.txt and sitemap.xml - let's add those to improve SEO
  - https://story.xyz/robots.txt
  -  https://story.xyz/sitemap.xml

**Comment by franckc** [comment]
@rolandpo Friendly ping. This would be a good issue for you to look at - it's impacting our site's SEO so marketing is escalating as high priority. Thanks :)

**Comment by rolandpo** [comment]
fix in #13

**Comment by nickick** [comment]
Merged #13 in
