### ISSUE TITLE
Broken link from originprotocol.com/vi/blog to article

### ISSUE THREAD

**Issue by rmcn15** [OriginProtocol/story.xyz#27]
The August token holder update in vietnamese is only viewable from the direct URL: 
https://www.originprotocol.com/vi/bao-cao-thang-8-origin-protocol 

The blog card shows here, but doesn't load when you click on it: https://www.originprotocol.com/vi/blog

**Comment by franckc** [comment]
Weird. It works for me: https://www.loom.com/share/9590eee556a149c7abb3485bafe309dc?sid=ce7b21d5-6bb9-4a27-992c-728df61c5278

**Comment by rmcn15** [comment]
Odd, works for me now too. Zoe initially pointed this out and I was able to replicate, but the site may have needed some time to update the page (I just re-published this morning). Don't think any action is needed but will let the team know if the issue persists.

**Comment by franckc** [comment]
Could be some caching related delays. Closing for now.
